### ISSUE TITLE
Documentation update required to specify the mandatory cloud_type parameter value as aws 

### ISSUE THREAD

**Issue by arcprabh** [openshift-scale/kraken#46]
Scenario - Enable node scenarios for an OCP cluster on a non aws cloud type

 Updated the cloud_type as openstack in the scenarios/node_scenarios_example.yml file

```
node_scenarios:
  - actions:                                                        # node chaos scenarios to be injected
 #   - node_stop_start_scenario
    - stop_start_kubelet_scenario
 #   - node_crash_scenario
    node_name: worker-0                                                      # node on which scenario has to be injected
    label_selector: node-role.kubernetes.io/worker                  # when node_name is not specified, a node with matching label_selector is selected for node chaos scenario injection
    instance_kill_count: 1                                          # number of times to inject each scenario under actions
    timeout: 120                                                    # duration to wait for completion of node scenario injection
    cloud_type: openstack                                                 # cloud type on which Kubernetes/OpenShift runs
```

Issue seen: Script fails when any value other than aws is specified in cloud_type.

```
[root@rails1 kraken]# python3 run_kraken.py --config config/config.yaml
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
2020-11-09 06:23:01,238 [INFO] Starting kraken
2020-11-09 06:23:01,244 [INFO] Initializing client to talk to the Kubernetes cluster
2020-11-09 06:23:03,448 [INFO] Fetching cluster info
2020-11-09 06:23:04,360 [INFO] 
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.1     True        False         11d     Cluster version is 4.6.1
Kubernetes master is running at https://api.chaos-arc46.redhat.com:6443
2020-11-09 06:23:04,361 [INFO] Daemon mode not enabled, will run through 1 iterations
2020-11-09 06:23:04,361 [INFO] Executing scenarios for iteration 0
Traceback (most recent call last):
  File "run_kraken.py", line 298, in <module>
    main(options.cfg)
  File "run_kraken.py", line 244, in main
    node_scenario_object)
  File "run_kraken.py", line 48, in inject_node_scenario
    node_scenario_object.stop_start_kubelet_scenario(instance_kill_count, node, timeout)
AttributeError: 'NoneType' object has no attribute 'stop_start_kubelet_scenario'
```

**Comment by arcprabh** [comment]
@paigerube14

**Comment by mffiedler** [comment]
hi @arcprabh Node scenarios are currently AWS-only .   See #40 and #41 for early work on Azure and GCP

**Comment by arcprabh** [comment]
> hi @arcprabh Node scenarios are currently AWS-only . See #40 and #41 for early work on Azure and GCP
> 
> See https://github.com/openshift-scale/kraken/blob/master/docs/node_scenarios.md for documentation that only AWS is supported right now.

In the same link, the below point is also mentioned and it doesnt work for these 2 cases.

NOTE: The stop_start_kubelet_scenario and node_crash_scenario scenarios are supported as they are independent of the cloud platform

**Comment by paigerube14** [comment]
@arcprabh we have added a way for cloud types that are currently not supported to still be able to use the node crash and stop kubelet scenarios.

The documentation has been updated to show [this](https://github.com/openshift-scale/kraken/blob/master/docs/node_scenarios.md)
**NOTE: The node_crash_scenario and stop_kubelet_scenario scenario is supported independent of the cloud platform.

Use 'generic' or do not add the 'cloud_type' key to your scenario if your cluster is not set up using one of the current supported cloud types**

Please let me us know if you have issues with this. Thanks

**Comment by chaitanyaenr** [comment]
Hello @arcprabh, we have more support for node scenarios for various cloud providers including OpenStack. Please let us know if the issue still persists. Thanks.

**Comment by pravin-dsilva** [comment]
I was working with Archana on these tests. I have run node scenarios on my cluster using Openstack provider. This can be closed. Thanks.
