### ISSUE TITLE
Node scenario fails asking for region name even if aws cli is installed.

### ISSUE THREAD

**Issue by arcprabh** [openshift-scale/kraken#47]
Scenario: Node scenario using kraken tool
Set cloud_type as aws on non aws cloud provider. 

File: scenarios/node_scenarios_example.yml

```
node_scenarios:
  - actions:                                                        # node chaos scenarios to be injected
 #   - node_stop_start_scenario
    - stop_start_kubelet_scenario
 #   - node_crash_scenario
    node_name: worker-0                                                      # node on which scenario has to be injected
    label_selector: node-role.kubernetes.io/worker                  # when node_name is not specified, a node with matching label_selector is selected for node chaos scenario injection
    instance_kill_count: 1                                          # number of times to inject each scenario under actions
    timeout: 120                                                    # duration to wait for completion of node scenario injection
    cloud_type: aws                                                 # cloud type on which Kubernetes/OpenShift runs
```

Issue seen:

```
[root@rails1 kraken]# python3 run_kraken.py --config config/config.yaml
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
                               

2020-11-09 06:50:42,571 [INFO] Starting kraken
2020-11-09 06:50:42,577 [INFO] Initializing client to talk to the Kubernetes cluster
2020-11-09 06:50:44,678 [INFO] Fetching cluster info
2020-11-09 06:50:46,239 [INFO] 
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.6.1     True        False         11d     Cluster version is 4.6.1
Kubernetes master is running at https://api.chaos-arc46.redhat.com:6443

2020-11-09 06:50:46,240 [INFO] Daemon mode not enabled, will run through 1 iterations

2020-11-09 06:50:46,240 [INFO] Executing scenarios for iteration 0
Traceback (most recent call last):
  File "run_kraken.py", line 298, in <module>
    main(options.cfg)
  File "run_kraken.py", line 240, in main
    node_scenario_object = get_node_scenario_object(node_scenario)
  File "run_kraken.py", line 21, in get_node_scenario_object
    return aws_node_scenarios()
  File "/root/chaos/kraken/kraken/node_actions/aws_node_scenarios.py", line 66, in __init__
    self.aws = AWS()
  File "/root/chaos/kraken/kraken/node_actions/aws_node_scenarios.py", line 12, in __init__
    self.boto_client = boto3.client('ec2')
  File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 153, in compute_client_args
    s3_config=s3_config,
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 218, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/args.py", line 301, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by arcprabh** [comment]
@paigerube14

**Comment by paigerube14** [comment]
The issue here is that you also need to configure the aws cli with your specific aws credentials. This definitely needs to be added to the documentation. Will cover that in a PR specific for this issue.

**Comment by paigerube14** [comment]
@arcprabh I have updated the documentation to further clarify the set up needed for aws. If you don't have an AWS account, the issue now becomes the same as https://github.com/openshift-scale/kraken/issues/46, correct?

**Comment by arcprabh** [comment]
> @arcprabh I have updated the documentation to further clarify the set up needed for aws. If you don't have an AWS account, the issue now becomes the same as #46, correct?

yes right.

**Comment by chaitanyaenr** [comment]
Closing this since we are tracking the issue in https://github.com/openshift-scale/kraken/issues/46. Thanks.
